"""add seeking inputs to artists

Revision ID: 5beec60bde34
Revises: 6069a613780f
Create Date: 2020-08-15 04:16:44.203409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5beec60bde34'
down_revision = '6069a613780f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_description', sa.String(length=500), nullable=True))
    op.add_column('artists', sa.Column('seeking_venue', sa.Boolean()))

    op.execute('UPDATE artists SET seeking_venue = False WHERE seeking_venue IS NULL;')

    op.alter_column('artists', sa.Column('seeking_venue', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'seeking_venue')
    op.drop_column('artists', 'seeking_description')
    # ### end Alembic commands ###
